[build]
command = "" # no build step
publish = "." # publish the folder that has index.html


# No-cache for HTML & config → every deploy is instantly visible
[[headers]]
for = "/index.html"
[headers.values]
Cache-Control = "no-store"


[[headers]]
for = "/access.html"
[headers.values]
Cache-Control = "no-store"


[[headers]]
for = "/config.json"
[headers.values]
Cache-Control = "no-store"


# Aggressive cache for everything else (images, js bundles if you add them later)
[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"